### EDA OF THE MOVIE DATASET

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# load the dataset

movies = pd.read_csv('data/TMDB_all_movies.csv')

In [4]:
movies.head()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,budget,imdb_id,...,director,director_of_photography,writers,producers,music_composer,imdb_rating,imdb_votes,poster_path,keywords,certification_us
0,2,Ariel,7.106,371.0,Released,1988-10-21,0.0,73.0,0.0,tt0094675,...,Aki Kaurismäki,Timo Salminen,Aki Kaurismäki,Aki Kaurismäki,NaN,7.4,9822.0,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,"prison|underdog|helsinki, finland|factory work...",NaN
1,3,Shadows in Paradise,7.300,439.0,Released,1986-10-17,0.0,74.0,0.0,tt0092149,...,Aki Kaurismäki,Timo Salminen,Aki Kaurismäki,Mika Kaurismäki,NaN,7.4,8690.0,/nj01hspawPof0mJmlgfjuLyJuRN.jpg,"helsinki, finland|salesclerk|garbage",NR
2,5,Four Rooms,5.905,2851.0,Released,1995-12-09,4257354.0,98.0,4000000.0,tt0113101,...,"Quentin Tarantino, Robert Rodriguez, Alexandre...","Phil Parmet, Guillermo Navarro, Rodrigo García...","Quentin Tarantino, Robert Rodriguez, Alexandre...","Quentin Tarantino, Lawrence Bender, Alexandre ...",Combustible Edison,6.7,117022.0,/75aHn1NOYXh4M7L5shoeQ6NGykP.jpg,hotel|new year's eve|witch|bet|sperm|hotel roo...,R
3,6,Judgment Night,6.500,370.0,Released,1993-10-15,12136938.0,109.0,21000000.0,tt0107286,...,Stephen Hopkins,Peter Levy,"Lewis Colick, Jere Cunningham","Lloyd Segan, Gene Levy, Marilyn Vance",Alan Silvestri,6.6,21118.0,/3rvvpS9YPM5HB2f4HYiNiJVtdam.jpg,"drug dealer|chicago, illinois|escape|one night...",R
4,8,Life in Loops (A Megacities RMX),7.200,30.0,Released,2006-01-01,0.0,80.0,42000.0,tt0825671,...,Timo Novotny,Wolfgang Thaler,"Timo Novotny, Michael Glawogger","Timo Novotny, Ulrich Gehmacher",NaN,8.1,285.0,/7ln81BRnPR2wqxuITZxEciCe1lc.jpg,megacities,NaN

In [5]:
# print columns

print(movies.columns)
print(movies.info())
print(movies.shape)

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'budget', 'imdb_id', 'original_language',
       'original_title', 'overview', 'popularity', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'cast', 'director', 'director_of_photography', 'writers', 'producers',
       'music_composer', 'imdb_rating', 'imdb_votes', 'poster_path',
       'keywords', 'certification_us'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1212040 entries, 0 to 1212039
Data columns (total 30 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   id                       1212040 non-null  int64
 1   title                    1212029 non-null  object
 2   vote_average             1212040 non-null  float64
 3   vote_count               1212040 non-null  float64
 4   status                   1212040 non-null  object
 5   release_date             1083448 non-null  object
 6   revenue                  1212040 non-null  float64
 7   runtime                  1212040 non-null  float64
 8   budget                   1212040 non-null  float64
 9   imdb_id                  673027 non-null   object
 10  original_language        1212040 non-null  object
 11  original_title           1212030 non-null  object
 12  overview                 1025901 non-null  object
 13  popularity               1212040 non-null  float64
 14  tagline                  184943 non-null   object
 15  genres                   885936 non-null   object
 16  production_companies     584237 non-null   object
 17  production_countries     762209 non-null   object
 18  spoken_languages         769971 non-null   object
 19  cast                     827230 non-null   object
 20  director                 1016732 non-null  object
 21  director_of_photography  328325 non-null   object
 22  writers                  613827 non-null   object
 23  producers                415970 non-null   object
 24  music_composer           138495 non-null   object
 25  imdb_rating              472230 non-null   float64
 26  imdb_votes               472230 non-null   float64
 27  poster_path              915105 non-null   object
 28  keywords                 341333 non-null   object
 29  certification_us         91765 non-null    object
dtypes: float64(8), int64(1), object(21)
memory usage: 277.4+ MB
None
(1212040, 30)

In [8]:

movies.isnull().sum().sort_values(ascending=False)

certification_us           1120275
music_composer             1073545
tagline                    1027097
director_of_photography     883715
keywords                    870707
producers                   796070
imdb_votes                  739810
imdb_rating                 739810
production_companies        627803
writers                     598213
imdb_id                     539013
production_countries        449831
spoken_languages            442069
cast                        384810
genres                      326104
poster_path                 296935
director                    195308
overview                    186139
release_date                128592
title                           11
original_title                  10
popularity                       0
id                               0
original_language                0
runtime                          0
budget                           0
revenue                          0
vote_average                     0
vote_count                       0
status                           0
dtype: int64

In [9]:
# check current count of movies in the dataset
print("Current count of movies in the dataset:", len(movies))

Current count of movies in the dataset: 1212040

In [10]:
# removing duplicates
movies.drop_duplicates(inplace=True)
print("Count of movies after removing duplicates:", len(movies))

Count of movies after removing duplicates: 1212040

In [11]:
# no of movies containing null values in the dataset
print("Count of movies containing null values in the dataset:", len(movies[movies.isnull().any(axis=1)]))

Count of movies containing null values in the dataset: 1194849

In [12]:
print(movies.columns)

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'budget', 'imdb_id', 'original_language',
       'original_title', 'overview', 'popularity', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'cast', 'director', 'director_of_photography', 'writers', 'producers',
       'music_composer', 'imdb_rating', 'imdb_votes', 'poster_path',
       'keywords', 'certification_us'],
      dtype='object')

In [13]:
cols_to_keep = [
    'id',
    'title',
    'overview',
    'genres',
    'keywords',
    'cast',
    'director',
    'runtime',
    'release_date',
    'imdb_rating',
    'vote_count',
    'popularity',
    'poster_path',
    'original_language'
]

movies = movies[cols_to_keep]

In [15]:
before = movies.shape[0]

movies = movies.drop_duplicates()

after = movies.shape[0]

print("Removed:", before - after)

Removed: 0

In [16]:
before = movies.shape[0]

movies = movies.dropna(
    subset=[
        'title',
        'overview',
        'genres',
        'release_date'
    ]
)

after = movies.shape[0]

print("Removed:", before - after)
print("Remaining:", after)

Removed: 480122
Remaining: 731918

In [17]:
movies['keywords'] = movies['keywords'].fillna('')
movies['cast'] = movies['cast'].fillna('')
movies['director'] = movies['director'].fillna('')
movies['imdb_rating'] = movies['imdb_rating'].fillna(0)

In [18]:
movies.isnull().sum().sort_values(ascending=False)

poster_path          111725
id                        0
overview                  0
genres                    0
keywords                  0
title                     0
cast                      0
director                  0
release_date              0
runtime                   0
imdb_rating               0
vote_count                0
popularity                0
original_language         0
dtype: int64

In [19]:
# check realease date for interstellar
print(movies[movies['title'] == 'Interstellar'])

           id         title  \
96317  157336  Interstellar

                                                overview  \
96317  The adventures of a group of explorers who mak...

                                  genres  \
96317  Adventure, Drama, Science Fiction

                                                keywords  \
96317  spacecraft|race against time|artificial intell...

                                                    cast           director  \
96317  Matthew McConaughey, Anne Hathaway, Michael Ca...  Christopher Nolan

       runtime release_date  imdb_rating  vote_count  popularity  \
96317    169.0   2014-11-05          8.7     40070.0      66.699

                            poster_path original_language
96317  /yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg                en

In [20]:
movies['release_date'] = pd.to_datetime(
    movies['release_date'],
    errors='coerce'
)

In [22]:
future_movies = movies[
    movies['release_date'].dt.year > 2026
]

future_movies[['title', 'release_date']].head(20)

                                                    title release_date
15428   Reuben: What Happens in Aldershot Stays in Ald...   2027-06-04
124958                                           Avatar 4   2029-12-19
259741                                           Avatar 5   2031-12-17
282255                                            Shrek 5   2027-06-30
311513                                    The Nightingale   2027-02-11
369343           The Resurrection of the Christ: Part One   2027-05-06
387355                                           F.A.S.T.   2027-04-22
410566                                Children of Liberty   2027-02-10
430754                            The Thomas Crown Affair   2027-03-04
430760                                        Hello Kitty   2028-07-20
435380                         Children of Blood and Bone   2027-01-14
452906                                             Dragon   2027-06-10
461139                                 High in the Clouds   2027-07-07
528710                          Oh, the Places You'll Go!   2028-03-16
533581                                       Fast Forever   2028-03-16
571352                                The Batman: Part II   2027-09-30
630878                        Night of The Abandoned City   2027-01-28
641914                Spider-Man: Beyond the Spider-Verse   2027-06-17
647832                                           Vāranāsi   2027-04-07
667428                     Sidi Kaba and the Gateway Home   2027-04-14

In [23]:
future_movies.shape[0]

377

In [24]:
movies = movies[
    movies['release_date'].dt.year <= 2026
]

print(
    movies['release_date'].dt.year.max()
)

2026

In [26]:
movies['runtime'].describe()

count    731541.000000
mean         57.808106
std          56.251095
min           0.000000
25%          12.000000
50%          60.000000
75%          91.000000
max       14400.000000
Name: runtime, dtype: float64

In [27]:
movies['vote_count'].describe()

count    731541.000000
mean         36.875172
std         469.350958
min           0.000000
25%           0.000000
50%           0.000000
75%           3.000000
max       40070.000000
Name: vote_count, dtype: float64

In [28]:
movies[
    ['title', 'runtime']
].sort_values(
    'runtime',
    ascending=False
).head(20)

                                                     title  runtime
142890                                Modern Times Forever  14400.0
500464                          Svalbard minutt for minutt  13319.0
159196                                           Cinématon  12480.0
115328                                        Beijing 2003   9000.0
119792                        Giant 600 Cartoon Collection   3720.0
137425                                     Five-Year Diary   2160.0
516381                                  Grandmother Martha   1452.0
87861                                            The Clock   1440.0
406122                                   24 Hours of Happy   1440.0
372026   Hollywood Remembers - Hollywoods Greatest Scre...   1273.0
422792                                       The Innocence   1265.0
65866                             Andy Warhol Screen Tests   1108.0
517740   Dmitri Shostakovich - Complete Symphonies & Co...   1082.0
186780                                150 Cartoon Classics   1035.0
406718                                  Portrait de groupe   1020.0
371466                        Jornal Português (1938-1951)   1018.0
488294                   Phenomenal: The Best of AJ Styles   1004.0
1147397                            The World Ends With You    999.0
1199969                                The Katabasis of...    999.0
281555                                           Logistics    999.0

In [30]:
movies.shape

(368465, 14)

In [31]:
print("Current:", len(movies))

print(">= 10 votes :", (movies['vote_count'] >= 10).sum())
print(">= 50 votes :", (movies['vote_count'] >= 50).sum())
print(">= 100 votes:", (movies['vote_count'] >= 100).sum())
print(">= 500 votes:", (movies['vote_count'] >= 500).sum())

Current: 368465
>= 10 votes : 86929
>= 50 votes : 33171
>= 100 votes: 21797
>= 500 votes: 7754

In [32]:
movies = movies[movies['vote_count'] >= 100]

print(movies.shape)

(21797, 14)

In [33]:
movies['title'].duplicated().sum()

np.int64(1208)

In [34]:
before = movies.shape[0]

movies = movies.sort_values(
    'vote_count',
    ascending=False
)

movies = movies.drop_duplicates(
    subset='title',
    keep='first'
)

after = movies.shape[0]

print("Removed:", before - after)
print("Remaining:", after)

Removed: 1208
Remaining: 20589

In [35]:
movies['id'].duplicated().sum()

np.int64(0)

In [36]:
movies.to_csv(
    "clean_movies.csv",
    index=False
)

In [37]:
movies.shape

(20589, 14)

In [38]:
movies[['genres', 'keywords', 'cast', 'director']].head(3)

,genres,keywords,cast,director
96317,"Adventure, Drama, Science Fiction",spacecraft|race against time|artificial intell...,"Matthew McConaughey, Anne Hathaway, Michael Ca...",Christopher Nolan
16312,"Action, Science Fiction, Adventure",mission|dreams|kidnapping|spy|allegory|intelle...,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...",Christopher Nolan
14413,"Science Fiction, Action, Adventure",new york city|superhero|shield|based on comic|...,"Robert Downey Jr., Chris Evans, Mark Ruffalo, ...",Joss Whedon

In [39]:
movies['tags'] = (
    movies['overview'].fillna('') + ' ' +
    movies['genres'].fillna('') + ' ' +
    movies['keywords'].fillna('') + ' ' +
    movies['cast'].fillna('') + ' ' +
    movies['director'].fillna('')
)

print(movies.iloc[0]['tags'][:500])

The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage. Adventure, Drama, Science Fiction spacecraft|race against time|artificial intelligence (a.i.)|nasa|time warp|dystopia|expedition|time travel|space travel|wormhole|famine|hibernation|black hole|quantum mechanics|family relationships|space|planet|astronaut|scientist|single father|space station|gravity|

In [40]:
movies['tags'] = movies['tags'].str.lower()
print(movies.iloc[0]['tags'][:300])

the adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage. adventure, drama, science fiction spacecraft|race against time|artificial intelligence (a.i.)|nasa|ti

In [41]:
movies['tags'] = movies['tags'].str.lower()

In [42]:
movies.head()

,id,title,overview,genres,keywords,cast,director,runtime,release_date,imdb_rating,vote_count,popularity,poster_path,original_language,tags
96317,157336,Interstellar,The adventures of a group of explorers who mak...,"Adventure, Drama, Science Fiction",spacecraft|race against time|artificial intell...,"Matthew McConaughey, Anne Hathaway, Michael Ca...",Christopher Nolan,169.0,2014-11-05,8.7,40070.0,66.6990,/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg,en,the adventures of a group of explorers who mak...
16312,27205,Inception,"Cobb, a skilled thief who commits corporate es...","Action, Science Fiction, Adventure",mission|dreams|kidnapping|spy|allegory|intelle...,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...",Christopher Nolan,148.0,2010-07-15,8.8,39398.0,30.2831,/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg,en,"cobb, a skilled thief who commits corporate es..."
14413,24428,The Avengers,When an unexpected enemy emerges and threatens...,"Science Fiction, Action, Adventure",new york city|superhero|shield|based on comic|...,"Robert Downey Jr., Chris Evans, Mark Ruffalo, ...",Joss Whedon,143.0,2012-04-25,8.0,38435.0,43.6909,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,en,when an unexpected enemy emerges and threatens...
116,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"Action, Crime, Thriller",sadism|chaos|secret identity|crime fighter|sup...,"Christian Bale, Heath Ledger, Aaron Eckhart, M...",Christopher Nolan,152.0,2008-07-16,9.1,35938.0,43.9582,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,en,batman raises the stakes in his war on crime. ...
12035,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","Science Fiction, Action, Adventure",paraplegic|attachment to nature|culture clash|...,"Sam Worthington, Zoe Saldaña, Sigourney Weaver...",James Cameron,162.0,2009-12-16,7.9,34083.0,30.1990,/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg,en,"in the 22nd century, a paraplegic marine is di..."

In [43]:
(movies['tags'].str.len() == 0).sum()

np.int64(0)

In [44]:
movies_recommender = movies[
    [
        'id',
        'title',
        'tags',
        'imdb_rating',
        'poster_path'
    ]
]

movies_recommender.head(5)

,id,title,tags,imdb_rating,poster_path
96317,157336,Interstellar,the adventures of a group of explorers who mak...,8.7,/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg
16312,27205,Inception,"cobb, a skilled thief who commits corporate es...",8.8,/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg
14413,24428,The Avengers,when an unexpected enemy emerges and threatens...,8.0,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg
116,155,The Dark Knight,batman raises the stakes in his war on crime. ...,9.1,/qJ2tW6WMUDux911r6m7haRef0WH.jpg
12035,19995,Avatar,"in the 22nd century, a paraplegic marine is di...",7.9,/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg

In [45]:
movies_recommender.shape

(20589, 5)

In [46]:
movies_recommender['tags'].str.split().apply(len).describe()

count    20589.000000
mean       124.883433
std         56.589850
min         11.000000
25%         86.000000
50%        114.000000
75%        151.000000
max       1105.000000
Name: tags, dtype: float64

### MODEL BUILDING

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words='english'
)

vectors = tfidf.fit_transform(
    movies_recommender['tags']
)

print(vectors.shape)

(20589, 5000)

In [48]:
from sklearn.metrics.pairwise import cosine_similarity

In [49]:
similarity = cosine_similarity(vectors)

In [50]:
similarity.shape

(20589, 20589)

In [52]:
similarity.nbytes / (1024**3)

3.158352680504322

In [53]:
movies_recommender.to_pickle("movies.pkl")

In [54]:
import os

print(
    os.path.getsize("movies.pkl") / (1024 * 1024)
)

19.650872230529785

In [55]:
import pickle

pickle.dump(
    vectors,
    open("vectors.pkl", "wb")
)

In [56]:
import os

print(
    os.path.getsize("vectors.pkl") / (1024 * 1024)
)

14.634647369384766

In [57]:
pickle.dump(
    tfidf,
    open("tfidf.pkl", "wb")
)

In [58]:
import os

print(
    os.path.getsize("tfidf.pkl") / (1024 * 1024)
)

0.17247867584228516

In [59]:
movies_recommender[
    movies_recommender['title'] == 'Interstellar'
]

,id,title,tags,imdb_rating,poster_path
96317,157336,Interstellar,the adventures of a group of explorers who mak...,8.7,/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg

In [60]:
idx = movies_recommender[
    movies_recommender['title'] == 'Interstellar'
].index[0]

print(idx)

96317

In [61]:
movies_recommender = movies_recommender.reset_index(drop=True)

In [62]:
idx = movies_recommender[
    movies_recommender['title'] == 'Interstellar'
].index[0]

print(idx)

0

In [63]:
from sklearn.metrics.pairwise import cosine_similarity

idx = 0

distances = cosine_similarity(
    vectors[idx],
    vectors
).flatten()

In [64]:
distances.shape

(20589,)

In [66]:
similar_movies = sorted(
    list(enumerate(distances)),
    key=lambda x: x[1],
    reverse=True
)

similar_movies[:10]

[(0, np.float64(0.9999999999999999)),
 (17375, np.float64(0.3877108565309098)),
 (131, np.float64(0.3875968000875841)),
 (6337, np.float64(0.3794619986066565)),
 (6264, np.float64(0.3788704816310767)),
 (6395, np.float64(0.3647741196982566)),
 (1505, np.float64(0.3382368635412112)),
 (19283, np.float64(0.3325347149711215)),
 (2632, np.float64(0.3268917092605804)),
 (127, np.float64(0.31889311796920333))]

In [67]:
for i in similar_movies[1:11]:
    print(
        movies_recommender.iloc[i[0]].title
    )

Doppelgänger
Gravity
Stowaway
Return to Space
Silent Running
Zathura: A Space Adventure
Marooned
The Midnight Sky
Alien
Approaching the Unknown

In [68]:
movie = movies_recommender[
    movies_recommender['title'] == 'Doppelgänger'
]

movie[['title']]

              title
17375  Doppelgänger

In [69]:
movies[
    movies['title'] == 'Doppelgänger'
][['title', 'genres', 'keywords', 'overview']]

,title,genres,keywords,overview
25662,Doppelgänger,Science Fiction,space travel|space mission|space|astronaut|tra...,A planet is discovered in the same orbit as Ea...

In [73]:
def recommend(movie_name):

    idx = movies_recommender[
        movies_recommender['title'] == movie_name
    ].index[0]

    distances = cosine_similarity(
        vectors[idx],
        vectors
    ).flatten()

    similar_movies = sorted(
        list(enumerate(distances)),
        key=lambda x: x[1],
        reverse=True
    )[1:6]

    recommendations = []

    for movie in similar_movies:
        recommendations.append(
            movies_recommender.iloc[movie[0]].title
        )

    return recommendations

In [74]:
recommend("Interstellar")

['Doppelgänger', 'Gravity', 'Stowaway', 'Return to Space', 'Silent Running']

In [75]:
movies_recommender.iloc[17375]

id                                                         40430
title                                               Doppelgänger
tags           a planet is discovered in the same orbit as ea...
imdb_rating                                                  6.3
poster_path                     /tW7Dr74ovic9wTAqoeRZy2SQ96L.jpg
Name: 17375, dtype: object

In [78]:
def recommend(movie_name):

    idx = movies_recommender[
        movies_recommender['title'] == movie_name
    ].index[0]

    distances = cosine_similarity(
        vectors[idx],
        vectors
    ).flatten()

    similar_movies = sorted(
        list(enumerate(distances)),
        key=lambda x: x[1],
        reverse=True
    )[1:6]

    recommendations = []

    for movie in similar_movies:

        movie_data = movies_recommender.iloc[movie[0]]

        recommendations.append({
            "title": movie_data["title"],
            "rating": float(movie_data["imdb_rating"]),
            "poster": movie_data["poster_path"]
        })

        
    return recommendations

In [79]:
recommend("Interstellar")

[{'title': 'Doppelgänger',
  'rating': 6.3,
  'poster': '/tW7Dr74ovic9wTAqoeRZy2SQ96L.jpg'},
 {'title': 'Gravity',
  'rating': 7.7,
  'poster': '/kZ2nZw8D681aphje8NJi8EfbL1U.jpg'},
 {'title': 'Stowaway',
  'rating': 5.7,
  'poster': '/eFyRjhJfhNgM565U2mwEp5YUUOv.jpg'},
 {'title': 'Return to Space',
  'rating': 7.3,
  'poster': '/yUN0g7gJwr2JhqNZBYJS2obkxU2.jpg'},
 {'title': 'Silent Running',
  'rating': 6.6,
  'poster': '/ahasZ5HILZHtlrl6cbXgpfk0y8H.jpg'}]

In [80]:
BASE_URL = "https://image.tmdb.org/t/p/w500"

print(
    BASE_URL +
    recommend("Interstellar")[1]["poster"]
)

https://image.tmdb.org/t/p/w500/kZ2nZw8D681aphje8NJi8EfbL1U.jpg

In [81]:
from sklearn.metrics.pairwise import cosine_similarity

def recommend(movie_name, top_n=5):

    # Check if movie exists
    matching_movies = movies_recommender[
        movies_recommender['title'].str.lower() == movie_name.lower()
    ]

    if matching_movies.empty:
        return {
            "status": "error",
            "message": f"Movie '{movie_name}' not found."
        }

    try:
        idx = matching_movies.index[0]

        distances = cosine_similarity(
            vectors[idx],
            vectors
        ).flatten()

        similar_movies = sorted(
            list(enumerate(distances)),
            key=lambda x: x[1],
            reverse=True
        )[1:top_n+1]

        recommendations = []

        for movie in similar_movies:

            movie_data = movies_recommender.iloc[movie[0]]

            recommendations.append({
                "title": movie_data["title"],
                "rating": float(movie_data["imdb_rating"]),
                "poster": movie_data["poster_path"]
            })

        return {
            "status": "success",
            "recommendations": recommendations
        }

    except Exception as e:
        return {
            "status": "error",
            "message": str(e)
        }

In [82]:
recommend("Interstellar")

{'status': 'success',
 'recommendations': [{'title': 'Doppelgänger',
   'rating': 6.3,
   'poster': '/tW7Dr74ovic9wTAqoeRZy2SQ96L.jpg'},
  {'title': 'Gravity',
   'rating': 7.7,
   'poster': '/kZ2nZw8D681aphje8NJi8EfbL1U.jpg'},
  {'title': 'Stowaway',
   'rating': 5.7,
   'poster': '/eFyRjhJfhNgM565U2mwEp5YUUOv.jpg'},
  {'title': 'Return to Space',
   'rating': 7.3,
   'poster': '/yUN0g7gJwr2JhqNZBYJS2obkxU2.jpg'},
  {'title': 'Silent Running',
   'rating': 6.6,
   'poster': '/ahasZ5HILZHtlrl6cbXgpfk0y8H.jpg'}]}

In [83]:
recommend("interstellar")

{'status': 'success',
 'recommendations': [{'title': 'Doppelgänger',
   'rating': 6.3,
   'poster': '/tW7Dr74ovic9wTAqoeRZy2SQ96L.jpg'},
  {'title': 'Gravity',
   'rating': 7.7,
   'poster': '/kZ2nZw8D681aphje8NJi8EfbL1U.jpg'},
  {'title': 'Stowaway',
   'rating': 5.7,
   'poster': '/eFyRjhJfhNgM565U2mwEp5YUUOv.jpg'},
  {'title': 'Return to Space',
   'rating': 7.3,
   'poster': '/yUN0g7gJwr2JhqNZBYJS2obkxU2.jpg'},
  {'title': 'Silent Running',
   'rating': 6.6,
   'poster': '/ahasZ5HILZHtlrl6cbXgpfk0y8H.jpg'}]}

In [84]:
recommend("asdasdasd")

{'status': 'error', 'message': "Movie 'asdasdasd' not found."}

In [93]:
recommend("The Dark Knight")

{'status': 'success',
 'recommendations': [{'title': 'The Dark Knight Rises',
   'rating': 8.4,
   'poster': '/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg'},
  {'title': 'Batman Begins',
   'rating': 8.2,
   'poster': '/sPX89Td70IDDjVr85jdSBb4rWGr.jpg'},
  {'title': 'Batman Forever',
   'rating': 5.5,
   'poster': '/i0fJS8M5UKoETjjJ0zwUiKaR8tr.jpg'},
  {'title': 'Law Abiding Citizen',
   'rating': 7.4,
   'poster': '/fcEXcip7v0O1ndV4VUdFqJSqbOg.jpg'},
  {'title': 'Batman',
   'rating': 7.5,
   'poster': '/cij4dd21v2Rk2YtUQbV5kW69WB2.jpg'}]}

In [94]:
from sklearn.metrics.pairwise import cosine_similarity

def recommend(movie_name, top_n=5):

    # Check if movie exists
    matching_movies = movies_recommender[
        movies_recommender['title'].str.lower() == movie_name.lower()
    ]

    if matching_movies.empty:
        return {
            "status": "error",
            "message": f"Movie '{movie_name}' not found."
        }

    try:
        idx = matching_movies.index[0]

        distances = cosine_similarity(
            vectors[idx],
            vectors
        ).flatten()

        similar_movies = sorted(
            list(enumerate(distances)),
            key=lambda x: x[1],
            reverse=True
        )[1:top_n+1]

        recommendations = []


        for movie in similar_movies:

            movie_data = movies_recommender.iloc[movie[0]]

            recommendations.append({
        "title": movie_data["title"],
        "rating": float(movie_data["imdb_rating"]),
        "similarity": float(movie[1]),
        "poster": movie_data["poster_path"]
        })

        return {
            "status": "success",
            "recommendations": recommendations
        }

    except Exception as e:
        return {
            "status": "error",
            "message": str(e)
        }

In [95]:
recommend("Avatar")

{'status': 'success',
 'recommendations': [{'title': 'Avatar: Fire and Ash',
   'rating': 7.2,
   'similarity': 0.25512733307016433,
   'poster': '/bRBeSHfGHwkEpImlhxPmOcUsaeg.jpg'},
  {'title': 'Avatar: The Way of Water',
   'rating': 7.5,
   'similarity': 0.2296610812658148,
   'poster': '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg'},
  {'title': 'Alien',
   'rating': 8.4,
   'similarity': 0.2170927290399954,
   'poster': '/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg'},
  {'title': 'Cosmic Sin',
   'rating': 2.5,
   'similarity': 0.20997084895079332,
   'poster': '/6Wm7P6y22UZA40QuPYHyWyJ6leI.jpg'},
  {'title': 'Aliens',
   'rating': 8.4,
   'similarity': 0.209863253364655,
   'poster': '/r1x5JGpyqZU8PYhbs4UcrO1Xb6x.jpg'}]}

In [96]:
from sklearn.metrics.pairwise import cosine_similarity

def recommend(movie_name, top_n=5):

    # Check if movie exists
    matching_movies = movies_recommender[
        movies_recommender['title'].str.lower() == movie_name.lower()
    ]

    if matching_movies.empty:
        return {
            "status": "error",
            "message": f"Movie '{movie_name}' not found."
        }

    try:
        idx = matching_movies.index[0]

        # Similarity with all movies
        distances = cosine_similarity(
            vectors[idx],
            vectors
        ).flatten()

        # Combine similarity + IMDb rating
        scored_movies = []

        for i, similarity in enumerate(distances):

            if i == idx:
                continue

            movie_data = movies_recommender.iloc[i]

            imdb_score = float(movie_data["imdb_rating"]) / 10

            final_score = (
                0.9 * similarity +
                0.1 * imdb_score
            )

            scored_movies.append(
                (i, final_score)
            )

        # Sort by final score
        similar_movies = sorted(
            scored_movies,
            key=lambda x: x[1],
            reverse=True
        )[:top_n]

        recommendations = []

        for movie in similar_movies:

            movie_data = movies_recommender.iloc[movie[0]]

            recommendations.append({
                "title": movie_data["title"],
                "rating": float(movie_data["imdb_rating"]),
                "score": round(float(movie[1]), 4),
                "poster": movie_data["poster_path"]
            })

        return {
            "status": "success",
            "recommendations": recommendations
        }

    except Exception as e:
        return {
            "status": "error",
            "message": str(e)
        }

In [97]:
recommend("Avatar")

{'status': 'success',
 'recommendations': [{'title': 'Avatar: Fire and Ash',
   'rating': 7.2,
   'score': 0.3016,
   'poster': '/bRBeSHfGHwkEpImlhxPmOcUsaeg.jpg'},
  {'title': 'Avatar: The Way of Water',
   'rating': 7.5,
   'score': 0.2817,
   'poster': '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg'},
  {'title': 'Alien',
   'rating': 8.4,
   'score': 0.2794,
   'poster': '/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg'},
  {'title': 'Aliens',
   'rating': 8.4,
   'score': 0.2729,
   'poster': '/r1x5JGpyqZU8PYhbs4UcrO1Xb6x.jpg'},
  {'title': 'Planet of the Vampires',
   'rating': 6.2,
   'score': 0.2445,
   'poster': '/bPpfT4r9HtHcri0eIknqpewoewM.jpg'}]}

In [98]:
movies_recommender = movies_recommender.reset_index(drop=True)

In [99]:
movies_recommender.index[:5]

RangeIndex(start=0, stop=5, step=1)

In [100]:
movies_recommender.to_pickle("movies.pkl")